# -*- coding: utf-8 -*-
import time
from functools import partial

from PyQt5 import QtCore
################################################################################
## Form generated from reading UI file 'mainwindowrGNAmM.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import resource_rc
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1182, 853)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/logo/icon/logo.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color: rgb(55, 81, 134);")
        MainWindow.setIconSize(QSize(24, 24))
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        icon1 = QIcon()
        icon1.addFile(u":/file/icon/file.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action.setIcon(icon1)
        self.action_2 = QAction(MainWindow)
        self.action_2.setObjectName(u"action_2")
        icon2 = QIcon()
        icon2.addFile(u":/run/icon/run.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_2.setIcon(icon2)
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        icon3 = QIcon()
        icon3.addFile(u":/over/icon/over.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_3.setIcon(icon3)
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        icon4 = QIcon()
        icon4.addFile(u":/compose type/icon/compose.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_4.setIcon(icon4)
        self.actionlogo = QAction(MainWindow)
        self.actionlogo.setObjectName(u"actionlogo")
        icon5 = QIcon()
        icon5.addFile(u":/logo/icon/logo.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionlogo.setIcon(icon5)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy1)
        self.gridLayout_13 = QGridLayout(self.widget_2)
        self.gridLayout_13.setObjectName(u"gridLayout_13")
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.widget_4 = QWidget(self.widget_2)
        self.widget_4.setObjectName(u"widget_4")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy2)
        self.widget_4.setMinimumSize(QSize(0, 0))
        self.widget_4.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.gridLayout_10 = QGridLayout(self.widget_4)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.tabWidget = QTabWidget(self.widget_4)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setStyleSheet(u"background-color: rgb(139, 146, 166);")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        sizePolicy2.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy2)
        self.gridLayout_11 = QGridLayout(self.tab)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.horizontalLayout_13 = QHBoxLayout()
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalSpacer_30 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_13.addItem(self.horizontalSpacer_30)

        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)

        self.horizontalLayout_13.addWidget(self.label)

        self.label_9 = QLabel(self.tab)
        self.label_9.setObjectName(u"label_9")
        sizePolicy2.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy2)

        self.horizontalLayout_13.addWidget(self.label_9)

        self.horizontalSpacer_31 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_13.addItem(self.horizontalSpacer_31)


        self.gridLayout_11.addLayout(self.horizontalLayout_13, 0, 0, 1, 1)

        self.horizontalLayout_17 = QHBoxLayout()
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalSpacer_36 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_17.addItem(self.horizontalSpacer_36)

        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        sizePolicy2.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy2)

        self.horizontalLayout_17.addWidget(self.label_3)

        self.label_10 = QLabel(self.tab)
        self.label_10.setObjectName(u"label_10")
        sizePolicy2.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy2)

        self.horizontalLayout_17.addWidget(self.label_10)

        self.horizontalSpacer_37 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_17.addItem(self.horizontalSpacer_37)


        self.gridLayout_11.addLayout(self.horizontalLayout_17, 1, 0, 1, 1)

        self.horizontalLayout_18 = QHBoxLayout()
        self.horizontalLayout_18.setObjectName(u"horizontalLayout_18")
        self.horizontalSpacer_38 = QSpacerItem(40, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_18.addItem(self.horizontalSpacer_38)

        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        sizePolicy2.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy2)

        self.horizontalLayout_18.addWidget(self.label_4)

        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        sizePolicy2.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy2)

        self.horizontalLayout_18.addWidget(self.label_11)

        self.horizontalSpacer_39 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_18.addItem(self.horizontalSpacer_39)


        self.gridLayout_11.addLayout(self.horizontalLayout_18, 2, 0, 1, 1)

        self.tabWidget.addTab(self.tab, "")

        self.gridLayout_10.addWidget(self.tabWidget, 0, 0, 1, 1)


        self.gridLayout_5.addWidget(self.widget_4, 2, 0, 1, 1)

        self.widget = QWidget(self.widget_2)
        self.widget.setObjectName(u"widget")
        self.widget.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.gridLayout_2 = QGridLayout(self.widget)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.widget_10 = QWidget(self.widget)
        self.widget_10.setObjectName(u"widget_10")
        sizePolicy1.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy1)
        self.widget_10.setStyleSheet(u"background-color: rgb(139, 146, 166);")
        self.gridLayout_3 = QGridLayout(self.widget_10)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalSpacer_9 = QSpacerItem(13, 40, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_9)

        self.widget_5 = QWidget(self.widget_10)
        self.widget_5.setObjectName(u"widget_5")
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy3)
        self.gridLayout_12 = QGridLayout(self.widget_5)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4 = QGridLayout()
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.horizontalLayout_20 = QHBoxLayout()
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(u"horizontalLayout_20")
        self.horizontalLayout_20.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.label_31 = QLabel(self.widget_5)
        self.label_31.setObjectName(u"label_31")
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)

        self.horizontalLayout_20.addWidget(self.label_31)

        self.label_32 = QLabel(self.widget_5)
        self.label_32.setObjectName(u"label_32")
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)

        self.horizontalLayout_20.addWidget(self.label_32)

        self.toolButton_4 = QToolButton(self.widget_5)
        self.toolButton_4.setObjectName(u"toolButton_4")

        self.horizontalLayout_20.addWidget(self.toolButton_4)


        self.gridLayout_4.addLayout(self.horizontalLayout_20, 1, 0, 1, 1)

        self.label_6 = QLabel(self.widget_5)
        self.label_6.setObjectName(u"label_6")
        sizePolicy2.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy2)

        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)


        self.gridLayout_12.addLayout(self.gridLayout_4, 0, 0, 1, 1)


        self.horizontalLayout.addWidget(self.widget_5)

        self.horizontalSpacer_13 = QSpacerItem(27, 40, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_13)

        self.pushButton_11 = QPushButton(self.widget_10)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setEnabled(True)
        sizePolicy3.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy3)
        self.pushButton_11.setMinimumSize(QSize(50, 0))
        font = QFont()
        font.setPointSize(11)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setLayoutDirection(Qt.LeftToRight)
        self.pushButton_11.setStyleSheet(u"background-color: rgb(139, 146, 166);")
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setIconSize(QSize(18, 18))
        self.pushButton_11.setAutoDefault(False)
        self.pushButton_11.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton_11)

        self.horizontalSpacer_12 = QSpacerItem(27, 40, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_12)

        self.pushButton_12 = QPushButton(self.widget_10)
        self.pushButton_12.setObjectName(u"pushButton_12")
        sizePolicy3.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy3)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setIconSize(QSize(18, 18))
        self.pushButton_12.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton_12)

        self.horizontalSpacer_14 = QSpacerItem(27, 40, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_14)

        self.pushButton_13 = QPushButton(self.widget_10)
        self.pushButton_13.setObjectName(u"pushButton_13")
        sizePolicy3.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy3)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setIcon(icon4)
        self.pushButton_13.setIconSize(QSize(18, 18))
        self.pushButton_13.setFlat(True)

        self.horizontalLayout.addWidget(self.pushButton_13)

        self.horizontalSpacer_8 = QSpacerItem(605, 40, QSizePolicy.Preferred, QSizePolicy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_8)


        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)


        self.gridLayout_2.addWidget(self.widget_10, 0, 0, 1, 1)


        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 2)

        self.stackedWidget_13 = QStackedWidget(self.widget_2)
        self.stackedWidget_13.setObjectName(u"stackedWidget_13")
        sizePolicy3.setHeightForWidth(self.stackedWidget_13.sizePolicy().hasHeightForWidth())
        self.stackedWidget_13.setSizePolicy(sizePolicy3)
        self.stackedWidget_13.setMinimumSize(QSize(0, 0))
        self.stackedWidget_13.setMaximumSize(QSize(16777215, 16777215))
        self.stackedWidget_13.setStyleSheet(u"background-color: rgb(175, 175, 175);")
        self.stackedWidget_13Page1 = QWidget()
        self.stackedWidget_13Page1.setObjectName(u"stackedWidget_13Page1")
        self.gridLayout_8 = QGridLayout(self.stackedWidget_13Page1)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.tabWidget_2 = QTabWidget(self.stackedWidget_13Page1)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setStyleSheet(u"background-color: rgb(139, 146, 166);")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_17 = QGridLayout(self.tab_2)
        self.gridLayout_17.setObjectName(u"gridLayout_17")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.groupBox = QGroupBox(self.tab_2)
        self.groupBox.setObjectName(u"groupBox")
        self.formLayout = QFormLayout(self.groupBox)
        self.formLayout.setObjectName(u"formLayout")
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label_5)

        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.comboBox)


        self.verticalLayout.addWidget(self.groupBox)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalSpacer = QSpacerItem(10, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer)

        self.ptn_ok = QPushButton(self.tab_2)
        self.ptn_ok.setObjectName(u"ptn_ok")
        sizePolicy.setHeightForWidth(self.ptn_ok.sizePolicy().hasHeightForWidth())
        self.ptn_ok.setSizePolicy(sizePolicy)

        self.horizontalLayout_3.addWidget(self.ptn_ok)

        self.horizontalSpacer_2 = QSpacerItem(10, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.ptn_cancel = QPushButton(self.tab_2)
        self.ptn_cancel.setObjectName(u"ptn_cancel")
        sizePolicy.setHeightForWidth(self.ptn_cancel.sizePolicy().hasHeightForWidth())
        self.ptn_cancel.setSizePolicy(sizePolicy)

        self.horizontalLayout_3.addWidget(self.ptn_cancel)

        self.horizontalSpacer_3 = QSpacerItem(10, 20, QSizePolicy.Fixed, QSizePolicy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_3)


        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)


        self.gridLayout_17.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.tabWidget_2.addTab(self.tab_2, "")

        self.gridLayout_8.addWidget(self.tabWidget_2, 0, 0, 1, 1)

        self.stackedWidget_13.addWidget(self.stackedWidget_13Page1)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.gridLayout_14 = QGridLayout(self.page_4)
        self.gridLayout_14.setObjectName(u"gridLayout_14")
        self.tabWidget_3 = QTabWidget(self.page_4)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setStyleSheet(u"background-color: rgb(139, 146, 166);")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget_3.addTab(self.tab_5, "")

        self.gridLayout_14.addWidget(self.tabWidget_3, 0, 0, 1, 1)

        self.stackedWidget_13.addWidget(self.page_4)

        self.gridLayout_5.addWidget(self.stackedWidget_13, 1, 1, 2, 1)

        self.stackedWidget_3 = QStackedWidget(self.widget_2)
        self.stackedWidget_3.setObjectName(u"stackedWidget_3")
        sizePolicy1.setHeightForWidth(self.stackedWidget_3.sizePolicy().hasHeightForWidth())
        self.stackedWidget_3.setSizePolicy(sizePolicy1)
        self.stackedWidget_3.setMinimumSize(QSize(0, 0))
        self.stackedWidget_3.setMaximumSize(QSize(16777215, 16777215))
        self.stackedWidget_3.setStyleSheet(u"background-color: rgb(113, 113, 113);")
        self.stackedWidget_3.setLineWidth(1)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.gridLayout_9 = QGridLayout(self.page)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.widget_p1 = QWidget(self.page)
        self.widget_p1.setObjectName(u"widget_p1")
        self.label_p1 = QLabel(self.widget_p1)
        self.label_p1.setObjectName(u"label_p1")
        self.label_p1.setGeometry(QRect(20, 20, 54, 12))
        self.openGLWidget_p1 = QOpenGLWidget(self.widget_p1)
        self.openGLWidget_p1.setObjectName(u"openGLWidget_p1")
        self.openGLWidget_p1.setGeometry(QRect(140, 0, 721, 581))
        self.pushButton_p1_3 = QPushButton(self.widget_p1)
        self.pushButton_p1_3.setObjectName(u"pushButton_p1_3")
        self.pushButton_p1_3.setGeometry(QRect(840, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p1_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p1_3.setSizePolicy(sizePolicy)
        self.pushButton_p1_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p1_3.setIcon(icon2)
        self.pushButton_p1_2 = QPushButton(self.widget_p1)
        self.pushButton_p1_2.setObjectName(u"pushButton_p1_2")
        self.pushButton_p1_2.setGeometry(QRect(800, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p1_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p1_2.setSizePolicy(sizePolicy)
        self.pushButton_p1_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p1_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p1_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p1_2.setBaseSize(QSize(0, 0))
        font1 = QFont()
        font1.setPointSize(9)
        font1.setKerning(True)
        self.pushButton_p1_2.setFont(font1)
        self.pushButton_p1_2.setAutoFillBackground(False)
        self.pushButton_p1_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p1_1 = QPushButton(self.widget_p1)
        self.pushButton_p1_1.setObjectName(u"pushButton_p1_1")
        self.pushButton_p1_1.setGeometry(QRect(740, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p1_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p1_1.setSizePolicy(sizePolicy)
        self.pushButton_p1_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p1_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p1_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p1_1.setAutoRepeatDelay(300)
        self.pushButton_p1_1.setAutoRepeatInterval(100)
        self.pushButton_p1_1.setAutoDefault(False)
        self.openGLWidget_p1.raise_()
        self.label_p1.raise_()
        self.pushButton_p1_3.raise_()
        self.pushButton_p1_2.raise_()
        self.pushButton_p1_1.raise_()

        self.gridLayout_9.addWidget(self.widget_p1, 0, 0, 1, 1)

        self.stackedWidget_3.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.horizontalLayout_2 = QHBoxLayout(self.page_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.widget_p2 = QWidget(self.page_2)
        self.widget_p2.setObjectName(u"widget_p2")
        self.label_p2 = QLabel(self.widget_p2)
        self.label_p2.setObjectName(u"label_p2")
        self.label_p2.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p2 = QOpenGLWidget(self.widget_p2)
        self.openGLWidget_p2.setObjectName(u"openGLWidget_p2")
        self.openGLWidget_p2.setGeometry(QRect(10, 0, 551, 591))
        self.pushButton_p2_3 = QPushButton(self.widget_p2)
        self.pushButton_p2_3.setObjectName(u"pushButton_p2_3")
        self.pushButton_p2_3.setGeometry(QRect(410, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p2_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p2_3.setSizePolicy(sizePolicy)
        self.pushButton_p2_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p2_3.setIcon(icon2)
        self.pushButton_p2_2 = QPushButton(self.widget_p2)
        self.pushButton_p2_2.setObjectName(u"pushButton_p2_2")
        self.pushButton_p2_2.setGeometry(QRect(370, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p2_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p2_2.setSizePolicy(sizePolicy)
        self.pushButton_p2_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p2_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p2_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p2_2.setBaseSize(QSize(0, 0))
        self.pushButton_p2_2.setFont(font1)
        self.pushButton_p2_2.setAutoFillBackground(False)
        self.pushButton_p2_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p2_1 = QPushButton(self.widget_p2)
        self.pushButton_p2_1.setObjectName(u"pushButton_p2_1")
        self.pushButton_p2_1.setGeometry(QRect(310, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p2_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p2_1.setSizePolicy(sizePolicy)
        self.pushButton_p2_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p2_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p2_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p2_1.setAutoRepeatDelay(300)
        self.pushButton_p2_1.setAutoRepeatInterval(100)
        self.pushButton_p2_1.setAutoDefault(False)
        self.openGLWidget_p2.raise_()
        self.label_p2.raise_()
        self.pushButton_p2_3.raise_()
        self.pushButton_p2_2.raise_()
        self.pushButton_p2_1.raise_()

        self.horizontalLayout_2.addWidget(self.widget_p2)

        self.widget_p3 = QWidget(self.page_2)
        self.widget_p3.setObjectName(u"widget_p3")
        self.label_p3 = QLabel(self.widget_p3)
        self.label_p3.setObjectName(u"label_p3")
        self.label_p3.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p3 = QOpenGLWidget(self.widget_p3)
        self.openGLWidget_p3.setObjectName(u"openGLWidget_p3")
        self.openGLWidget_p3.setGeometry(QRect(20, 0, 541, 591))
        self.pushButton_p3_3 = QPushButton(self.widget_p3)
        self.pushButton_p3_3.setObjectName(u"pushButton_p3_3")
        self.pushButton_p3_3.setGeometry(QRect(410, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p3_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p3_3.setSizePolicy(sizePolicy)
        self.pushButton_p3_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p3_3.setIcon(icon2)
        self.pushButton_p3_2 = QPushButton(self.widget_p3)
        self.pushButton_p3_2.setObjectName(u"pushButton_p3_2")
        self.pushButton_p3_2.setGeometry(QRect(370, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p3_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p3_2.setSizePolicy(sizePolicy)
        self.pushButton_p3_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p3_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p3_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p3_2.setBaseSize(QSize(0, 0))
        self.pushButton_p3_2.setFont(font1)
        self.pushButton_p3_2.setAutoFillBackground(False)
        self.pushButton_p3_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p3_1 = QPushButton(self.widget_p3)
        self.pushButton_p3_1.setObjectName(u"pushButton_p3_1")
        self.pushButton_p3_1.setGeometry(QRect(310, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p3_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p3_1.setSizePolicy(sizePolicy)
        self.pushButton_p3_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p3_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p3_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p3_1.setAutoRepeatDelay(300)
        self.pushButton_p3_1.setAutoRepeatInterval(100)
        self.pushButton_p3_1.setAutoDefault(False)
        self.openGLWidget_p3.raise_()
        self.label_p3.raise_()
        self.pushButton_p3_3.raise_()
        self.pushButton_p3_2.raise_()
        self.pushButton_p3_1.raise_()

        self.horizontalLayout_2.addWidget(self.widget_p3)

        self.stackedWidget_3.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.gridLayout_7 = QGridLayout(self.page_3)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.widget_p7 = QWidget(self.page_3)
        self.widget_p7.setObjectName(u"widget_p7")
        self.label_p7 = QLabel(self.widget_p7)
        self.label_p7.setObjectName(u"label_p7")
        self.label_p7.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p7 = QOpenGLWidget(self.widget_p7)
        self.openGLWidget_p7.setObjectName(u"openGLWidget_p7")
        self.openGLWidget_p7.setGeometry(QRect(90, 0, 341, 291))
        self.pushButton_p7_3 = QPushButton(self.widget_p7)
        self.pushButton_p7_3.setObjectName(u"pushButton_p7_3")
        self.pushButton_p7_3.setGeometry(QRect(410, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p7_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p7_3.setSizePolicy(sizePolicy)
        self.pushButton_p7_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p7_3.setIcon(icon2)
        self.pushButton_p7_2 = QPushButton(self.widget_p7)
        self.pushButton_p7_2.setObjectName(u"pushButton_p7_2")
        self.pushButton_p7_2.setGeometry(QRect(370, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p7_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p7_2.setSizePolicy(sizePolicy)
        self.pushButton_p7_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p7_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p7_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p7_2.setBaseSize(QSize(0, 0))
        self.pushButton_p7_2.setFont(font1)
        self.pushButton_p7_2.setAutoFillBackground(False)
        self.pushButton_p7_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p7_1 = QPushButton(self.widget_p7)
        self.pushButton_p7_1.setObjectName(u"pushButton_p7_1")
        self.pushButton_p7_1.setGeometry(QRect(310, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p7_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p7_1.setSizePolicy(sizePolicy)
        self.pushButton_p7_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p7_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p7_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p7_1.setAutoRepeatDelay(300)
        self.pushButton_p7_1.setAutoRepeatInterval(100)
        self.pushButton_p7_1.setAutoDefault(False)
        self.openGLWidget_p7.raise_()
        self.label_p7.raise_()
        self.pushButton_p7_3.raise_()
        self.pushButton_p7_2.raise_()
        self.pushButton_p7_1.raise_()

        self.gridLayout_6.addWidget(self.widget_p7, 1, 1, 1, 1)

        self.widget_p4 = QWidget(self.page_3)
        self.widget_p4.setObjectName(u"widget_p4")
        self.label_p4 = QLabel(self.widget_p4)
        self.label_p4.setObjectName(u"label_p4")
        self.label_p4.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p4 = QOpenGLWidget(self.widget_p4)
        self.openGLWidget_p4.setObjectName(u"openGLWidget_p4")
        self.openGLWidget_p4.setGeometry(QRect(90, 0, 341, 291))
        self.openGLWidget_p4.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p4_3 = QPushButton(self.widget_p4)
        self.pushButton_p4_3.setObjectName(u"pushButton_p4_3")
        self.pushButton_p4_3.setGeometry(QRect(410, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p4_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p4_3.setSizePolicy(sizePolicy)
        self.pushButton_p4_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p4_3.setIcon(icon2)
        self.pushButton_p4_2 = QPushButton(self.widget_p4)
        self.pushButton_p4_2.setObjectName(u"pushButton_p4_2")
        self.pushButton_p4_2.setGeometry(QRect(370, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p4_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p4_2.setSizePolicy(sizePolicy)
        self.pushButton_p4_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p4_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p4_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p4_2.setBaseSize(QSize(0, 0))
        self.pushButton_p4_2.setFont(font1)
        self.pushButton_p4_2.setAutoFillBackground(False)
        self.pushButton_p4_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p4_1 = QPushButton(self.widget_p4)
        self.pushButton_p4_1.setObjectName(u"pushButton_p4_1")
        self.pushButton_p4_1.setGeometry(QRect(310, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p4_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p4_1.setSizePolicy(sizePolicy)
        self.pushButton_p4_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p4_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p4_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p4_1.setAutoRepeatDelay(300)
        self.pushButton_p4_1.setAutoRepeatInterval(100)
        self.pushButton_p4_1.setAutoDefault(False)
        self.openGLWidget_p4.raise_()
        self.label_p4.raise_()
        self.pushButton_p4_3.raise_()
        self.pushButton_p4_2.raise_()
        self.pushButton_p4_1.raise_()

        self.gridLayout_6.addWidget(self.widget_p4, 0, 0, 1, 1)

        self.widget_p5 = QWidget(self.page_3)
        self.widget_p5.setObjectName(u"widget_p5")
        self.label_p5 = QLabel(self.widget_p5)
        self.label_p5.setObjectName(u"label_p5")
        self.label_p5.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p5 = QOpenGLWidget(self.widget_p5)
        self.openGLWidget_p5.setObjectName(u"openGLWidget_p5")
        self.openGLWidget_p5.setGeometry(QRect(90, 0, 341, 291))
        self.pushButton_p5_3 = QPushButton(self.widget_p5)
        self.pushButton_p5_3.setObjectName(u"pushButton_p5_3")
        self.pushButton_p5_3.setGeometry(QRect(410, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p5_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p5_3.setSizePolicy(sizePolicy)
        self.pushButton_p5_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p5_3.setIcon(icon2)
        self.pushButton_p5_2 = QPushButton(self.widget_p5)
        self.pushButton_p5_2.setObjectName(u"pushButton_p5_2")
        self.pushButton_p5_2.setGeometry(QRect(370, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p5_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p5_2.setSizePolicy(sizePolicy)
        self.pushButton_p5_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p5_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p5_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p5_2.setBaseSize(QSize(0, 0))
        self.pushButton_p5_2.setFont(font1)
        self.pushButton_p5_2.setAutoFillBackground(False)
        self.pushButton_p5_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p5_1 = QPushButton(self.widget_p5)
        self.pushButton_p5_1.setObjectName(u"pushButton_p5_1")
        self.pushButton_p5_1.setGeometry(QRect(310, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p5_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p5_1.setSizePolicy(sizePolicy)
        self.pushButton_p5_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p5_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p5_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p5_1.setAutoRepeatDelay(300)
        self.pushButton_p5_1.setAutoRepeatInterval(100)
        self.pushButton_p5_1.setAutoDefault(False)
        self.openGLWidget_p5.raise_()
        self.label_p5.raise_()
        self.pushButton_p5_3.raise_()
        self.pushButton_p5_2.raise_()
        self.pushButton_p5_1.raise_()

        self.gridLayout_6.addWidget(self.widget_p5, 0, 1, 1, 1)

        self.widget_p6 = QWidget(self.page_3)
        self.widget_p6.setObjectName(u"widget_p6")
        self.label_p6 = QLabel(self.widget_p6)
        self.label_p6.setObjectName(u"label_p6")
        self.label_p6.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p6 = QOpenGLWidget(self.widget_p6)
        self.openGLWidget_p6.setObjectName(u"openGLWidget_p6")
        self.openGLWidget_p6.setGeometry(QRect(90, 0, 341, 291))
        self.pushButton_p6_3 = QPushButton(self.widget_p6)
        self.pushButton_p6_3.setObjectName(u"pushButton_p6_3")
        self.pushButton_p6_3.setGeometry(QRect(410, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p6_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p6_3.setSizePolicy(sizePolicy)
        self.pushButton_p6_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p6_3.setIcon(icon2)
        self.pushButton_p6_2 = QPushButton(self.widget_p6)
        self.pushButton_p6_2.setObjectName(u"pushButton_p6_2")
        self.pushButton_p6_2.setGeometry(QRect(370, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p6_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p6_2.setSizePolicy(sizePolicy)
        self.pushButton_p6_2.setMinimumSize(QSize(0, 24))
        self.pushButton_p6_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p6_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p6_2.setBaseSize(QSize(0, 0))
        self.pushButton_p6_2.setFont(font1)
        self.pushButton_p6_2.setAutoFillBackground(False)
        self.pushButton_p6_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p6_1 = QPushButton(self.widget_p6)
        self.pushButton_p6_1.setObjectName(u"pushButton_p6_1")
        self.pushButton_p6_1.setGeometry(QRect(310, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p6_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p6_1.setSizePolicy(sizePolicy)
        self.pushButton_p6_1.setMinimumSize(QSize(0, 24))
        self.pushButton_p6_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p6_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p6_1.setAutoRepeatDelay(300)
        self.pushButton_p6_1.setAutoRepeatInterval(100)
        self.pushButton_p6_1.setAutoDefault(False)
        self.openGLWidget_p6.raise_()
        self.label_p6.raise_()
        self.pushButton_p6_3.raise_()
        self.pushButton_p6_2.raise_()
        self.pushButton_p6_1.raise_()

        self.gridLayout_6.addWidget(self.widget_p6, 1, 0, 1, 1)


        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)

        self.stackedWidget_3.addWidget(self.page_3)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.gridLayout_16 = QGridLayout(self.page_5)
        self.gridLayout_16.setObjectName(u"gridLayout_16")
        self.gridLayout_15 = QGridLayout()
        self.gridLayout_15.setObjectName(u"gridLayout_15")
        self.widget_p17 = QWidget(self.page_5)
        self.widget_p17.setObjectName(u"widget_p17")
        self.label_p17 = QLabel(self.widget_p17)
        self.label_p17.setObjectName(u"label_p17")
        self.label_p17.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p17 = QOpenGLWidget(self.widget_p17)
        self.openGLWidget_p17.setObjectName(u"openGLWidget_p17")
        self.openGLWidget_p17.setGeometry(QRect(40, 0, 241, 201))
        self.openGLWidget_p17.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p17_3 = QPushButton(self.widget_p17)
        self.pushButton_p17_3.setObjectName(u"pushButton_p17_3")
        self.pushButton_p17_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p17_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p17_3.setSizePolicy(sizePolicy)
        self.pushButton_p17_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p17_3.setIcon(icon2)
        self.pushButton_p17_2 = QPushButton(self.widget_p17)
        self.pushButton_p17_2.setObjectName(u"pushButton_p17_2")
        self.pushButton_p17_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p17_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p17_2.setSizePolicy(sizePolicy)
        self.pushButton_p17_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p17_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p17_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p17_2.setBaseSize(QSize(0, 0))
        self.pushButton_p17_2.setFont(font1)
        self.pushButton_p17_2.setAutoFillBackground(False)
        self.pushButton_p17_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p17_1 = QPushButton(self.widget_p17)
        self.pushButton_p17_1.setObjectName(u"pushButton_p17_1")
        self.pushButton_p17_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p17_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p17_1.setSizePolicy(sizePolicy)
        self.pushButton_p17_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p17_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p17_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p17_1.setAutoRepeatDelay(300)
        self.pushButton_p17_1.setAutoRepeatInterval(100)
        self.pushButton_p17_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p17, 2, 2, 1, 1)

        self.widget_p11 = QWidget(self.page_5)
        self.widget_p11.setObjectName(u"widget_p11")
        self.label_p11 = QLabel(self.widget_p11)
        self.label_p11.setObjectName(u"label_p11")
        self.label_p11.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p11 = QOpenGLWidget(self.widget_p11)
        self.openGLWidget_p11.setObjectName(u"openGLWidget_p11")
        self.openGLWidget_p11.setGeometry(QRect(40, 0, 241, 191))
        self.openGLWidget_p11.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p11_3 = QPushButton(self.widget_p11)
        self.pushButton_p11_3.setObjectName(u"pushButton_p11_3")
        self.pushButton_p11_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p11_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p11_3.setSizePolicy(sizePolicy)
        self.pushButton_p11_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p11_3.setIcon(icon2)
        self.pushButton_p11_2 = QPushButton(self.widget_p11)
        self.pushButton_p11_2.setObjectName(u"pushButton_p11_2")
        self.pushButton_p11_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p11_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p11_2.setSizePolicy(sizePolicy)
        self.pushButton_p11_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p11_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p11_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p11_2.setBaseSize(QSize(0, 0))
        self.pushButton_p11_2.setFont(font1)
        self.pushButton_p11_2.setAutoFillBackground(False)
        self.pushButton_p11_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p11_1 = QPushButton(self.widget_p11)
        self.pushButton_p11_1.setObjectName(u"pushButton_p11_1")
        self.pushButton_p11_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p11_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p11_1.setSizePolicy(sizePolicy)
        self.pushButton_p11_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p11_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p11_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p11_1.setAutoRepeatDelay(300)
        self.pushButton_p11_1.setAutoRepeatInterval(100)
        self.pushButton_p11_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p11, 0, 2, 1, 1)

        self.widget_p16 = QWidget(self.page_5)
        self.widget_p16.setObjectName(u"widget_p16")
        self.label_p16 = QLabel(self.widget_p16)
        self.label_p16.setObjectName(u"label_p16")
        self.label_p16.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p16 = QOpenGLWidget(self.widget_p16)
        self.openGLWidget_p16.setObjectName(u"openGLWidget_p16")
        self.openGLWidget_p16.setGeometry(QRect(40, 0, 241, 191))
        self.openGLWidget_p16.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p16_3 = QPushButton(self.widget_p16)
        self.pushButton_p16_3.setObjectName(u"pushButton_p16_3")
        self.pushButton_p16_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p16_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p16_3.setSizePolicy(sizePolicy)
        self.pushButton_p16_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p16_3.setIcon(icon2)
        self.pushButton_p16_2 = QPushButton(self.widget_p16)
        self.pushButton_p16_2.setObjectName(u"pushButton_p16_2")
        self.pushButton_p16_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p16_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p16_2.setSizePolicy(sizePolicy)
        self.pushButton_p16_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p16_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p16_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p16_2.setBaseSize(QSize(0, 0))
        self.pushButton_p16_2.setFont(font1)
        self.pushButton_p16_2.setAutoFillBackground(False)
        self.pushButton_p16_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p16_1 = QPushButton(self.widget_p16)
        self.pushButton_p16_1.setObjectName(u"pushButton_p16_1")
        self.pushButton_p16_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p16_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p16_1.setSizePolicy(sizePolicy)
        self.pushButton_p16_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p16_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p16_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p16_1.setAutoRepeatDelay(300)
        self.pushButton_p16_1.setAutoRepeatInterval(100)
        self.pushButton_p16_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p16, 2, 1, 1, 1)

        self.widget_p10 = QWidget(self.page_5)
        self.widget_p10.setObjectName(u"widget_p10")
        self.label_p10 = QLabel(self.widget_p10)
        self.label_p10.setObjectName(u"label_p10")
        self.label_p10.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p10 = QOpenGLWidget(self.widget_p10)
        self.openGLWidget_p10.setObjectName(u"openGLWidget_p10")
        self.openGLWidget_p10.setGeometry(QRect(40, 0, 241, 191))
        self.openGLWidget_p10.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p10_1 = QPushButton(self.widget_p10)
        self.pushButton_p10_1.setObjectName(u"pushButton_p10_1")
        self.pushButton_p10_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p10_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p10_1.setSizePolicy(sizePolicy)
        self.pushButton_p10_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p10_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p10_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p10_1.setAutoRepeatDelay(300)
        self.pushButton_p10_1.setAutoRepeatInterval(100)
        self.pushButton_p10_1.setAutoDefault(False)
        self.pushButton_p10_2 = QPushButton(self.widget_p10)
        self.pushButton_p10_2.setObjectName(u"pushButton_p10_2")
        self.pushButton_p10_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p10_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p10_2.setSizePolicy(sizePolicy)
        self.pushButton_p10_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p10_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p10_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p10_2.setBaseSize(QSize(0, 0))
        self.pushButton_p10_2.setFont(font1)
        self.pushButton_p10_2.setAutoFillBackground(False)
        self.pushButton_p10_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p10_3 = QPushButton(self.widget_p10)
        self.pushButton_p10_3.setObjectName(u"pushButton_p10_3")
        self.pushButton_p10_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p10_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p10_3.setSizePolicy(sizePolicy)
        self.pushButton_p10_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p10_3.setIcon(icon2)

        self.gridLayout_15.addWidget(self.widget_p10, 0, 1, 1, 1)

        self.widget_p15 = QWidget(self.page_5)
        self.widget_p15.setObjectName(u"widget_p15")
        self.label_p15 = QLabel(self.widget_p15)
        self.label_p15.setObjectName(u"label_p15")
        self.label_p15.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p15 = QOpenGLWidget(self.widget_p15)
        self.openGLWidget_p15.setObjectName(u"openGLWidget_p15")
        self.openGLWidget_p15.setGeometry(QRect(40, 0, 241, 191))
        self.openGLWidget_p15.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p15_3 = QPushButton(self.widget_p15)
        self.pushButton_p15_3.setObjectName(u"pushButton_p15_3")
        self.pushButton_p15_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p15_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p15_3.setSizePolicy(sizePolicy)
        self.pushButton_p15_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p15_3.setIcon(icon2)
        self.pushButton_p15_2 = QPushButton(self.widget_p15)
        self.pushButton_p15_2.setObjectName(u"pushButton_p15_2")
        self.pushButton_p15_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p15_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p15_2.setSizePolicy(sizePolicy)
        self.pushButton_p15_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p15_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p15_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p15_2.setBaseSize(QSize(0, 0))
        self.pushButton_p15_2.setFont(font1)
        self.pushButton_p15_2.setAutoFillBackground(False)
        self.pushButton_p15_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p15_1 = QPushButton(self.widget_p15)
        self.pushButton_p15_1.setObjectName(u"pushButton_p15_1")
        self.pushButton_p15_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p15_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p15_1.setSizePolicy(sizePolicy)
        self.pushButton_p15_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p15_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p15_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p15_1.setAutoRepeatDelay(300)
        self.pushButton_p15_1.setAutoRepeatInterval(100)
        self.pushButton_p15_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p15, 2, 0, 1, 1)

        self.widget_p12 = QWidget(self.page_5)
        self.widget_p12.setObjectName(u"widget_p12")
        self.label_p12 = QLabel(self.widget_p12)
        self.label_p12.setObjectName(u"label_p12")
        self.label_p12.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p12 = QOpenGLWidget(self.widget_p12)
        self.openGLWidget_p12.setObjectName(u"openGLWidget_p12")
        self.openGLWidget_p12.setGeometry(QRect(40, 0, 241, 191))
        self.openGLWidget_p12.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p12_3 = QPushButton(self.widget_p12)
        self.pushButton_p12_3.setObjectName(u"pushButton_p12_3")
        self.pushButton_p12_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p12_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p12_3.setSizePolicy(sizePolicy)
        self.pushButton_p12_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p12_3.setIcon(icon2)
        self.pushButton_p12_2 = QPushButton(self.widget_p12)
        self.pushButton_p12_2.setObjectName(u"pushButton_p12_2")
        self.pushButton_p12_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p12_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p12_2.setSizePolicy(sizePolicy)
        self.pushButton_p12_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p12_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p12_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p12_2.setBaseSize(QSize(0, 0))
        self.pushButton_p12_2.setFont(font1)
        self.pushButton_p12_2.setAutoFillBackground(False)
        self.pushButton_p12_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p12_1 = QPushButton(self.widget_p12)
        self.pushButton_p12_1.setObjectName(u"pushButton_p12_1")
        self.pushButton_p12_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p12_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p12_1.setSizePolicy(sizePolicy)
        self.pushButton_p12_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p12_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p12_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p12_1.setAutoRepeatDelay(300)
        self.pushButton_p12_1.setAutoRepeatInterval(100)
        self.pushButton_p12_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p12, 1, 0, 1, 1)

        self.widget_p13 = QWidget(self.page_5)
        self.widget_p13.setObjectName(u"widget_p13")
        self.label_p13 = QLabel(self.widget_p13)
        self.label_p13.setObjectName(u"label_p13")
        self.label_p13.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p13 = QOpenGLWidget(self.widget_p13)
        self.openGLWidget_p13.setObjectName(u"openGLWidget_p13")
        self.openGLWidget_p13.setGeometry(QRect(40, 0, 241, 201))
        self.openGLWidget_p13.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p13_3 = QPushButton(self.widget_p13)
        self.pushButton_p13_3.setObjectName(u"pushButton_p13_3")
        self.pushButton_p13_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p13_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p13_3.setSizePolicy(sizePolicy)
        self.pushButton_p13_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p13_3.setIcon(icon2)
        self.pushButton_p13_2 = QPushButton(self.widget_p13)
        self.pushButton_p13_2.setObjectName(u"pushButton_p13_2")
        self.pushButton_p13_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p13_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p13_2.setSizePolicy(sizePolicy)
        self.pushButton_p13_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p13_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p13_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p13_2.setBaseSize(QSize(0, 0))
        self.pushButton_p13_2.setFont(font1)
        self.pushButton_p13_2.setAutoFillBackground(False)
        self.pushButton_p13_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p13_1 = QPushButton(self.widget_p13)
        self.pushButton_p13_1.setObjectName(u"pushButton_p13_1")
        self.pushButton_p13_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p13_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p13_1.setSizePolicy(sizePolicy)
        self.pushButton_p13_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p13_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p13_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p13_1.setAutoRepeatDelay(300)
        self.pushButton_p13_1.setAutoRepeatInterval(100)
        self.pushButton_p13_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p13, 1, 1, 1, 1)

        self.widget_p14 = QWidget(self.page_5)
        self.widget_p14.setObjectName(u"widget_p14")
        self.label_p14 = QLabel(self.widget_p14)
        self.label_p14.setObjectName(u"label_p14")
        self.label_p14.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p14 = QOpenGLWidget(self.widget_p14)
        self.openGLWidget_p14.setObjectName(u"openGLWidget_p14")
        self.openGLWidget_p14.setGeometry(QRect(40, 0, 241, 191))
        self.openGLWidget_p14.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p14_3 = QPushButton(self.widget_p14)
        self.pushButton_p14_3.setObjectName(u"pushButton_p14_3")
        self.pushButton_p14_3.setGeometry(QRect(260, 0, 28, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p14_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p14_3.setSizePolicy(sizePolicy)
        self.pushButton_p14_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p14_3.setIcon(icon2)
        self.pushButton_p14_2 = QPushButton(self.widget_p14)
        self.pushButton_p14_2.setObjectName(u"pushButton_p14_2")
        self.pushButton_p14_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p14_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p14_2.setSizePolicy(sizePolicy)
        self.pushButton_p14_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p14_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p14_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p14_2.setBaseSize(QSize(0, 0))
        self.pushButton_p14_2.setFont(font1)
        self.pushButton_p14_2.setAutoFillBackground(False)
        self.pushButton_p14_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p14_1 = QPushButton(self.widget_p14)
        self.pushButton_p14_1.setObjectName(u"pushButton_p14_1")
        self.pushButton_p14_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p14_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p14_1.setSizePolicy(sizePolicy)
        self.pushButton_p14_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p14_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p14_1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p14_1.setAutoRepeatDelay(300)
        self.pushButton_p14_1.setAutoRepeatInterval(100)
        self.pushButton_p14_1.setAutoDefault(False)

        self.gridLayout_15.addWidget(self.widget_p14, 1, 2, 1, 1)

        self.widget_p9 = QWidget(self.page_5)
        self.widget_p9.setObjectName(u"widget_p9")
        self.widget_p9.setLayoutDirection(Qt.LeftToRight)
        self.widget_p9.setAutoFillBackground(False)
        self.label_p9 = QLabel(self.widget_p9)
        self.label_p9.setObjectName(u"label_p9")
        self.label_p9.setGeometry(QRect(20, 30, 54, 12))
        self.openGLWidget_p9 = QOpenGLWidget(self.widget_p9)
        self.openGLWidget_p9.setObjectName(u"openGLWidget_p9")
        self.openGLWidget_p9.setGeometry(QRect(40, 0, 241, 191))
        sizePolicy1.setHeightForWidth(self.openGLWidget_p9.sizePolicy().hasHeightForWidth())
        self.openGLWidget_p9.setSizePolicy(sizePolicy1)
        self.openGLWidget_p9.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p9_1 = QPushButton(self.widget_p9)
        self.pushButton_p9_1.setObjectName(u"pushButton_p9_1")
        self.pushButton_p9_1.setGeometry(QRect(160, 0, 60, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p9_1.sizePolicy().hasHeightForWidth())
        self.pushButton_p9_1.setSizePolicy(sizePolicy)
        self.pushButton_p9_1.setMinimumSize(QSize(60, 24))
        self.pushButton_p9_1.setMaximumSize(QSize(60, 24))
        self.pushButton_p9_1.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.pushButton_p9_1.setAutoRepeatDelay(300)
        self.pushButton_p9_1.setAutoRepeatInterval(100)
        self.pushButton_p9_1.setAutoDefault(False)
        self.pushButton_p9_2 = QPushButton(self.widget_p9)
        self.pushButton_p9_2.setObjectName(u"pushButton_p9_2")
        self.pushButton_p9_2.setGeometry(QRect(220, 0, 40, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p9_2.sizePolicy().hasHeightForWidth())
        self.pushButton_p9_2.setSizePolicy(sizePolicy)
        self.pushButton_p9_2.setMinimumSize(QSize(40, 24))
        self.pushButton_p9_2.setMaximumSize(QSize(40, 24))
        self.pushButton_p9_2.setSizeIncrement(QSize(0, 0))
        self.pushButton_p9_2.setBaseSize(QSize(0, 0))
        self.pushButton_p9_2.setFont(font1)
        self.pushButton_p9_2.setAutoFillBackground(False)
        self.pushButton_p9_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p9_3 = QPushButton(self.widget_p9)
        self.pushButton_p9_3.setObjectName(u"pushButton_p9_3")
        self.pushButton_p9_3.setGeometry(QRect(260, 0, 30, 24))
        sizePolicy.setHeightForWidth(self.pushButton_p9_3.sizePolicy().hasHeightForWidth())
        self.pushButton_p9_3.setSizePolicy(sizePolicy)
        self.pushButton_p9_3.setMinimumSize(QSize(30, 0))
        self.pushButton_p9_3.setMaximumSize(QSize(30, 16777215))
        self.pushButton_p9_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.pushButton_p9_3.setIcon(icon2)

        self.gridLayout_15.addWidget(self.widget_p9, 0, 0, 1, 1)


        self.gridLayout_16.addLayout(self.gridLayout_15, 0, 0, 1, 1)

        self.stackedWidget_3.addWidget(self.page_5)

        self.gridLayout_5.addWidget(self.stackedWidget_3, 1, 0, 1, 1)


        self.gridLayout_13.addLayout(self.gridLayout_5, 0, 1, 1, 1)


        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.pushButton_11.setDefault(False)
        self.stackedWidget_13.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.stackedWidget_3.setCurrentIndex(3)
        self.pushButton_p1_1.setDefault(False)
        self.pushButton_p2_1.setDefault(False)
        self.pushButton_p3_1.setDefault(False)
        self.pushButton_p7_1.setDefault(False)
        self.pushButton_p4_1.setDefault(False)
        self.pushButton_p5_1.setDefault(False)
        self.pushButton_p6_1.setDefault(False)
        self.pushButton_p17_1.setDefault(False)
        self.pushButton_p11_1.setDefault(False)
        self.pushButton_p16_1.setDefault(False)
        self.pushButton_p10_1.setDefault(False)
        self.pushButton_p15_1.setDefault(False)
        self.pushButton_p12_1.setDefault(False)
        self.pushButton_p13_1.setDefault(False)
        self.pushButton_p14_1.setDefault(False)
        self.pushButton_p9_1.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u5de5\u4e1a\u89c6\u89c9\u96c6\u6210\u5e73\u53f0", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.action.setToolTip(QCoreApplication.translate("MainWindow", u"file", None))
#endif // QT_CONFIG(tooltip)
        self.action_2.setText(QCoreApplication.translate("MainWindow", u"\u8fd0\u884c", None))
#if QT_CONFIG(tooltip)
        self.action_2.setToolTip(QCoreApplication.translate("MainWindow", u"run", None))
#endif // QT_CONFIG(tooltip)
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u505c\u6b62", None))
#if QT_CONFIG(tooltip)
        self.action_3.setToolTip(QCoreApplication.translate("MainWindow", u"over", None))
#endif // QT_CONFIG(tooltip)
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u6392\u7248", None))
#if QT_CONFIG(tooltip)
        self.action_4.setToolTip(QCoreApplication.translate("MainWindow", u"\u6392\u7248", None))
#endif // QT_CONFIG(tooltip)
        self.actionlogo.setText(QCoreApplication.translate("MainWindow", u"logo", None))
#if QT_CONFIG(tooltip)
        self.actionlogo.setToolTip(QCoreApplication.translate("MainWindow", u"logo", None))
#endif // QT_CONFIG(tooltip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\u4fe1\u606f\u5217\u8868", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.toolButton_4.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\u5de5\u7a0b\u540d\u79f0\u7f16\u53f7", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u" \u8fd0\u884c", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u" \u7ed3\u675f", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u" \u6392\u7248", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u76f8\u673a\u6570\u91cf", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\u6570\u91cf\uff1a", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"9", None))

        self.comboBox.setCurrentText(QCoreApplication.translate("MainWindow", u"9", None))
        self.ptn_ok.setText(QCoreApplication.translate("MainWindow", u"\u786e\u8ba4", None))
        self.ptn_cancel.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\u6392\u7248\u8bbe\u5b9a", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u8bbe\u5b9a", None))
        self.label_p1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p1_3.setText("")
        self.pushButton_p1_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p1_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p2_3.setText("")
        self.pushButton_p2_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p2_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p3_3.setText("")
        self.pushButton_p3_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p3_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p7.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p7_3.setText("")
        self.pushButton_p7_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p7_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p4_3.setText("")
        self.pushButton_p4_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p4_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p5.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p5_3.setText("")
        self.pushButton_p5_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p5_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p6.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p6_3.setText("")
        self.pushButton_p6_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p6_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p17.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p17_3.setText("")
        self.pushButton_p17_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p17_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p11.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p11_3.setText("")
        self.pushButton_p11_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p11_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p16.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p16_3.setText("")
        self.pushButton_p16_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p16_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p10.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p10_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.pushButton_p10_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p10_3.setText("")
        self.label_p15.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p15_3.setText("")
        self.pushButton_p15_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p15_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p12.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p12_3.setText("")
        self.pushButton_p12_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p12_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p13.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p13_3.setText("")
        self.pushButton_p13_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p13_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p14.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p14_3.setText("")
        self.pushButton_p14_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p14_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.label_p9.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.pushButton_p9_1.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u7f16\u8bd1", None))
        self.pushButton_p9_2.setText(QCoreApplication.translate("MainWindow", u"\u5168\u5c4f", None))
        self.pushButton_p9_3.setText("")
    # retranslateUi
